[package]
name = "sepl"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "2.0"
logos = "0.15"

[dependencies.uuid]
version = "1.17"
# Lets you generate random UUIDs
features = [
    "v4",
    "fast-rng"
]